#!/bin/sh
# =============================================================
# gh0stzk
# https://github.com/gh0stzk/dotfiles
# 24.04.2025
# =============================================================

wid=$1
class=$2
instance=$3
consequences=$4

result() {
    eval "$consequences"
    [ "$state" ] || echo "$1"
}

case "$class" in
    FloaTerm)
		result "state=floating center=on rectangle=696x399+0+0"
        ;;
    Updating)
		result "state=floating sticky=on center=on rectangle=390x405+0+0"
        ;;
	Scratch)
		result "state=floating focus=on sticky=on"
		;;
	RiceEditor)
		result "state=floating focus=on center=on"
		;;
    mpv)
		result "state=floating focus=on center=on rectangle=723x407+0+0"
        ;;
    Viewnior)
        result "state=floating focus=on center=on"
        ;;
    TelegramDesktop)
        result "desktop=^4 follow=on"
        ;;
    pavucontrol)
        result "state=floating center=on"
        ;;
    feh)
        result "state=floating"
        ;;
    ZapZap)
        result "desktop=^1 follow=on"
        ;;
    discord)
        result "desktop=^1 follow=on"
        ;;
    notion-desktop)
        result "desktop=^2 follow=on"
        ;;
    eu.betterbird.Betterbird)
        result "desktop=^3 follow=on"
        ;;
    Spotify)
        result "desktop=^5 follow=on"
        ;;
    steam)
        result "desktop=^5 follow=on"
        ;;
    Code)
        result "desktop=^7 follow=on"
        ;;
    dbgate)
        result "desktop=^8 follow=on"
        ;;
    zoom)
        if xprop -id "$wid" | grep -qE '_NET_WM_NAME\(UTF8_STRING\) = "zoom"| _NET_WM_NAME\(UTF8_STRING\) = "Settings"| _NET_WM_NAME\(UTF8_STRING\) = "Zoom Workplace - Free account" | _NET_WM_NAME\(UTF8_STRING\) = "zoom_linux_float_video_window"'; then
            result "state=floating"
        fi
        ;;
    wpp)
        if xprop -id "$wid" | grep -qE '_NET_WM_NAME\(UTF8_STRING\) = "WPS Presentation Slide Show'; then
            result "desktop=^6 state=floating follow=on"
        else
            result "state=tiled"
        fi
        ;;
esac

case "$instance" in
    Toolkit)
        result "state=floating sticky=on rectangle=500x290+1054+593"
        ;;
	YaziTerm)
		result "state=floating center=on rectangle=900x342+0+0"
		;;
	MusicTerm)
		result "state=floating center=on rectangle=656x343+0+0"
		;;
	FetchTerm)
		result "state=floating center=on rectangle=369x601+0+0"
		;;
esac
