watch_stylesheet: false
watch_config: true
debug: true

komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"

bars:
  status-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "bottom"
      center: true
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: true
      border_color: System 
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "90%"
      height: 36
    padding:
      top: -5
      left: 0
      bottom: 8
      right: 0
    widgets:
      left:
        [
          "win_button",
          "spacer",
          "cpu",
          "memory",
          "taskbar",
          "active_window",
        ] 
      center: [
          "komorebi_workspaces",
        ]
      right:
        [
          "media",
          "battery",
          "wifi",
          "volume",
          "reload_button",
          "clock",
          "wallpapers",
          "systray",
          "power_menu"
        ]

widgets:
  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "{volume_label} {space[used][percent]}"
        label_alt: "{volume_label} {space[used][gb]} / {space[total][gb]}"
        volume_label: "C"
        update_interval: 60 # Update interval in seconds
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec explorer C:\\"

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{title} - {artist}"
      max_field_size:
        label: 20
        label_alt: 30
      show_thumbnail: false
      controls_only: false
      controls_left: false
      hide_empty: true
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16 # Set to 0 for square corners
      icons:
        prev_track: "\udb83\udf28"
        next_track: "\udb83\udf27"
        play: "\uf04b"
        pause: "\udb80\udfe4"

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 16
      max_length_ellipsis: "..."
      monitor_exclusive: false

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>{percent}%"
      label_alt: "{icon} {percent}% | time: {time_remaining}"
      charging_options:
        icon_format: "{charging_icon}"

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%d %b %y, %H:%M}"
      label_alt: "{%A %d %B %Y, %H:%M}"
      #locale: 'en_EN' # Langugae for date, you can set your own, example fr_FR
      timezones: [] #Looking up time zone info from registry
      #timezones: ["America/Montreal"]
      callbacks:
        on_left: 'exec cmd /c start "" "%userprofile%\.config\yasb\notif.ahk"'

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_free}"
      label_alt: "<span>\uefc5</span> {virtual_mem_percent}%"
      update_interval: 10000
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "Komorebi Offline"
        label_workspace_btn: "\uea71"
        label_workspace_populated_btn: "\udb80\udea0"
        label_workspace_active_btn: "\udb82\udfaf"
        label_default_name: "{index}"
        label_zero_index: false
        hide_empty_workspaces: false
        hide_if_offline: false

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      wifi_icons:
        - "\udb82\udd2e" # 0% strength (no wifi)
        - "\udb82\udd1f" # 1-25% strength
        - "\udb82\udd22" # 26-50% strength
        - "\udb82\udd25" # 51-75% strength
        - "\udb82\udd28" # 76-100% strength. Alternate theming: \uf1eb
      callbacks:
        on_left: 'exec cmd /c start ms-availablenetworks:'
        on_right: 'exec cmd /c start "" "%userprofile%\.config\yasb\command.ahk"'

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: true
      blur: false
      blur_background: true
      animation_duration: 300 # Milisecond 
      button_row: 3 # Number of buttons in row, min 1 max 5
      buttons:
        lock: ["\uea75","Lock"]
        signout: ["\udb80\udf43","Sign out"]
        #sleep: ["\u23fe","Sleep"]
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        hibernate: ["\uf28e","Hibernate"]
        cancel: ["\udb81\udf3a","Cancel"]
        #force_shutdown: ["\uf011","Force Shut Down"]
        #force_restart: ["\uead2","Force Restart"]

  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      ignore_apps:
        processes: []
        titles: []
        classes: []

  win_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\ue62a"
      label_alt: "\ue62a"
      class_name: "system-widget"
      callbacks:
        on_left: "exec start_menu"

  spacer:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\udb80\uddd9"
      label_alt: "\udb80\uddd9"
      class_name: "spacer-widget"
  
  systray:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf107"
      label_alt: "\uf106"
      class_name: "systray-widget"
      callbacks:
        on_left: 'exec cmd /c start "" "%userprofile%\.config\yasb\tray.ahk"'

  reload_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf079"
      label_alt: "\uf079"
      class_name: "reload-widget"
      callbacks:
        on_left: "exec cd %userprofile% && ren komorebi.json komorebi_temp.json && ren komorebi.json.bak komorebi.json && ren komorebi_temp.json komorebi.json.bak && komorebic stop --whkd && komorebic start --whkd"

  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\ASUS\\Images" # Example path to folder with images
      change_automatically: false # Automatically change wallpaper
      update_interval: 60 # If change_automatically is true, update interval in seconds
      gallery:
          enabled: true
          blur: true
          image_width: 220
          image_per_page: 8
          show_buttons: false
          orientation: "portrait"
          image_spacing: 6
          lazy_load: true
          lazy_load_delay: 80
          lazy_load_fadein: 200
          image_corner_radius: 20
          enable_cache: true
      run_after: # List of functions to run after wallpaper is updated
        # - "wal -s -t -e -q -n -i {image}" # Example command to run after wallpaper is updated
        # - "cmd.exe /c start /min pwsh ./yasb.ps1" # Example command to run after wallpaper is updated